# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Rocky7842/android_kernel_xiaomi_sdm710
          kernel-dir: msm-4.9
          kernel-branch: lineage-23.0
          config: sdm670-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
